"""initial schema

Revision ID: 347e9f0d70f8
Revises: 
Create Date: 2026-07-15 03:05:58.784648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '347e9f0d70f8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_cart_items_product_id', table_name='cart_items')
    op.drop_index('idx_cart_items_user_id', table_name='cart_items')
    op.create_index('ix_cart_items_product_id', 'cart_items', ['product_id'], unique=False)
    op.create_index('ix_cart_items_user_id', 'cart_items', ['user_id'], unique=False)
    op.drop_index('idx_chat_messages_room_id', table_name='chat_messages')
    op.create_index('ix_chat_messages_room_id', 'chat_messages', ['room_id'], unique=False)
    op.drop_index('idx_chat_rooms_buyer_id', table_name='chat_rooms')
    op.drop_index('idx_chat_rooms_seller_id', table_name='chat_rooms')
    op.create_index('ix_chat_rooms_buyer_id', 'chat_rooms', ['buyer_id'], unique=False)
    op.create_index('ix_chat_rooms_seller_id', 'chat_rooms', ['seller_id'], unique=False)
    op.drop_index('idx_coupons_seller_id', table_name='coupons')
    op.create_index('ix_coupons_seller_id', 'coupons', ['seller_id'], unique=False)
    op.drop_index('idx_notifications_user_id_is_read', table_name='notifications')
    op.create_index('ix_notifications_user_id_is_read', 'notifications', ['user_id', 'is_read'], unique=False)
    op.drop_index('idx_order_items_order_id', table_name='order_items')
    op.drop_index('idx_order_items_seller_id', table_name='order_items')
    op.create_index('ix_order_items_order_id', 'order_items', ['order_id'], unique=False)
    op.create_index('ix_order_items_seller_id', 'order_items', ['seller_id'], unique=False)
    op.drop_index('idx_orders_payment_status', table_name='orders')
    op.drop_index('idx_orders_status', table_name='orders')
    op.create_index('ix_orders_payment_status', 'orders', ['payment_status'], unique=False)
    op.create_index('ix_orders_status', 'orders', ['status'], unique=False)
    op.drop_index('idx_payments_order_id', table_name='payments')
    op.drop_index('idx_payments_status', table_name='payments')
    op.drop_index('idx_payments_transaction_id', table_name='payments')
    op.create_index('ix_payments_order_id', 'payments', ['order_id'], unique=False)
    op.create_index('ix_payments_status', 'payments', ['status'], unique=False)
    op.create_index('ix_payments_transaction_id', 'payments', ['transaction_id'], unique=False)
    op.drop_index('idx_products_active_category', table_name='products')
    op.drop_index('idx_products_is_active', table_name='products')
    op.drop_index('idx_products_is_featured', table_name='products')
    op.drop_index('idx_products_rating_avg', table_name='products')
    op.drop_index('idx_products_sold_count', table_name='products')
    op.create_index('ix_products_is_active', 'products', ['is_active'], unique=False)
    op.create_index('ix_products_is_active_category', 'products', ['is_active', 'category_id'], unique=False)
    op.create_index('ix_products_is_featured', 'products', ['is_featured'], unique=False)
    op.create_index('ix_products_rating_avg', 'products', ['rating_avg'], unique=False)
    op.create_index('ix_products_sold_count', 'products', ['sold_count'], unique=False)
    op.drop_index('idx_reviews_product_id_user_id', table_name='reviews')
    op.drop_index('idx_reviews_user_id', table_name='reviews')
    op.create_index('ix_reviews_product_id_user_id', 'reviews', ['product_id', 'user_id'], unique=False)
    op.create_index('ix_reviews_user_id', 'reviews', ['user_id'], unique=False)
    op.drop_index('idx_wishlists_user_id_product_id', table_name='wishlists')
    op.create_unique_constraint('uq_wishlist_user_product', 'wishlists', ['user_id', 'product_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_wishlist_user_product', 'wishlists', type_='unique')
    op.create_index('idx_wishlists_user_id_product_id', 'wishlists', ['user_id', 'product_id'], unique=False)
    op.drop_index('ix_reviews_user_id', table_name='reviews')
    op.drop_index('ix_reviews_product_id_user_id', table_name='reviews')
    op.create_index('idx_reviews_user_id', 'reviews', ['user_id'], unique=False)
    op.create_index('idx_reviews_product_id_user_id', 'reviews', ['product_id', 'user_id'], unique=False)
    op.drop_index('ix_products_sold_count', table_name='products')
    op.drop_index('ix_products_rating_avg', table_name='products')
    op.drop_index('ix_products_is_featured', table_name='products')
    op.drop_index('ix_products_is_active_category', table_name='products')
    op.drop_index('ix_products_is_active', table_name='products')
    op.create_index('idx_products_sold_count', 'products', ['sold_count'], unique=False)
    op.create_index('idx_products_rating_avg', 'products', ['rating_avg'], unique=False)
    op.create_index('idx_products_is_featured', 'products', ['is_featured'], unique=False)
    op.create_index('idx_products_is_active', 'products', ['is_active'], unique=False)
    op.create_index('idx_products_active_category', 'products', ['is_active', 'category_id'], unique=False)
    op.drop_index('ix_payments_transaction_id', table_name='payments')
    op.drop_index('ix_payments_status', table_name='payments')
    op.drop_index('ix_payments_order_id', table_name='payments')
    op.create_index('idx_payments_transaction_id', 'payments', ['transaction_id'], unique=False)
    op.create_index('idx_payments_status', 'payments', ['status'], unique=False)
    op.create_index('idx_payments_order_id', 'payments', ['order_id'], unique=False)
    op.drop_index('ix_orders_status', table_name='orders')
    op.drop_index('ix_orders_payment_status', table_name='orders')
    op.create_index('idx_orders_status', 'orders', ['status'], unique=False)
    op.create_index('idx_orders_payment_status', 'orders', ['payment_status'], unique=False)
    op.drop_index('ix_order_items_seller_id', table_name='order_items')
    op.drop_index('ix_order_items_order_id', table_name='order_items')
    op.create_index('idx_order_items_seller_id', 'order_items', ['seller_id'], unique=False)
    op.create_index('idx_order_items_order_id', 'order_items', ['order_id'], unique=False)
    op.drop_index('ix_notifications_user_id_is_read', table_name='notifications')
    op.create_index('idx_notifications_user_id_is_read', 'notifications', ['user_id', 'is_read'], unique=False)
    op.drop_index('ix_coupons_seller_id', table_name='coupons')
    op.create_index('idx_coupons_seller_id', 'coupons', ['seller_id'], unique=False)
    op.drop_index('ix_chat_rooms_seller_id', table_name='chat_rooms')
    op.drop_index('ix_chat_rooms_buyer_id', table_name='chat_rooms')
    op.create_index('idx_chat_rooms_seller_id', 'chat_rooms', ['seller_id'], unique=False)
    op.create_index('idx_chat_rooms_buyer_id', 'chat_rooms', ['buyer_id'], unique=False)
    op.drop_index('ix_chat_messages_room_id', table_name='chat_messages')
    op.create_index('idx_chat_messages_room_id', 'chat_messages', ['room_id'], unique=False)
    op.drop_index('ix_cart_items_user_id', table_name='cart_items')
    op.drop_index('ix_cart_items_product_id', table_name='cart_items')
    op.create_index('idx_cart_items_user_id', 'cart_items', ['user_id'], unique=False)
    op.create_index('idx_cart_items_product_id', 'cart_items', ['product_id'], unique=False)
    # ### end Alembic commands ###
